<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Rate;
use App\Models\Currency;

class RatesSeeder extends Seeder
{
    public function run()
    {
        $rates = [
            //  1  /  plan  /  1  //
            [
                "status" => "active",
                "plan_id" => 1,
                "from" => 1,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 1,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 1,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 1,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],  
            //  1  /  plan  /  2  //
            [
                "status" => "active",
                "plan_id" => 2,
                "from" => 1,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 1,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 1,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 1,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  1  /  plan  /  3  //
            [
                "status" => "active",
                "plan_id" => 3,
                "from" => 1,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 1,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 1,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 1,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  2   //  plan   //  1  //
            [
                "status" => "active",
                "plan_id" => 1,
                "from" => 2,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 2,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 2,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 2,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],  
            //  2   //  plan   //  2  //
            [
                "status" => "active",
                "plan_id" => 2,
                "from" => 2,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 2,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 2,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 2,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  2   //  plan   //  3  //
            [
                "status" => "active",
                "plan_id" => 3,
                "from" => 2,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 2,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 2,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 2,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  3   //  plan   //  1  //
            [
                "status" => "active",
                "plan_id" => 1,
                "from" => 3,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 3,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 3,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 3,
                "to" => 5,
                "selling" => 1.1,
                "buying" => 1.03
            ],  
            //  3   //  plan   //  2  //
            [
                "status" => "active",
                "plan_id" => 2,
                "from" => 3,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 3,
                "to" => 2,
                "selling" => 1.1,
                "buying" => 1.07
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 3,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 3,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  3   //  plan   //  3  //
            [
                "status" => "active",
                "plan_id" => 3,
                "from" => 3,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 3,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 3,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 3,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  4   //  plan   //  1  //
            [
                "status" => "active",
                "plan_id" => 1,
                "from" => 4,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 4,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 4,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 4,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],  
            //  4   //  plan   //  2  //
            [
                "status" => "active",
                "plan_id" => 2,
                "from" => 4,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 4,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 4,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 4,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  4   //  plan   //  3  //
            [
                "status" => "active",
                "plan_id" => 3,
                "from" => 4,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 4,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 4,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 4,
                "to" => 5,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            
            //  5   //  plan   //  1  //
            [
                "status" => "active",
                "plan_id" => 1,
                "from" => 5,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 5,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 5,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 1,
                "from" => 5,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],  
            //  5   //  plan   //  2  //
            [
                "status" => "active",
                "plan_id" => 2,
                "from" => 5,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 5,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 5,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 2,
                "from" => 5,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            //  5   //  plan   //  3  //
            [
                "status" => "active",
                "plan_id" => 3,
                "from" => 5,
                "to" => 1,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 5,
                "to" => 2,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 5,
                "to" => 3,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
            [
                "status" => "inactive",
                "plan_id" => 3,
                "from" => 5,
                "to" => 4,
                "selling" => rand(1000, 3000),
                "buying" => rand(1000, 3000),
            ],
        ];

        foreach ($rates as $rate) {
          
            Rate::updateOrCreate(
                $rate
            );
        }
    }
}
